### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [pkindalov/Robo-friends#1]
.

**Comment by pkindalov** [comment]
Hi Arthur. Thank for your interest.
Can I ask you did you saw my portfolio on github, just to see my
experience. I am not sure if I have needed skills to help you, because I am
in process of learning.
For example I just learn about React and don't finished with redux yet.
I just want to know what are your expectations from me, for not
disappointing you.
Yes I like to learn and to try new things and to work on projects but I am
not sure if this is enough.
Also I would like to understand what technologies you use for the project.
If you use some framework like angular or react or something else. Can you
provide me more information about the idea of the project, technologies you
want or you use, yours expectations about me ? :)
